### ISSUE TITLE
Fixing Database Connection

### ISSUE THREAD

**Issue by MichaelGolebiowski** [MichaelGolebiowski/Tafe17S104#3]
The master branch (and subsequently all other branches) must be re-created due to some broken database connections in every version

**Comment by MichaelGolebiowski** [comment]
The master branch as well as branch feat_term1 have been re-created. Please re-create your branches and comment here when done.

**Comment by Eclipse2552** [comment]
Noice. Hopefully it'll stay fixed this time

**Comment by MichaelGolebiowski** [comment]
All branches have been fixed.
